---
- hosts: localhost
  gather_facts: no

  vars_files:
    - "vars/fromTerraform.yml"
    #- "vars/creds.json"

  vars:
    my_pass: []

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Register JSON variables for credentials and cluster
      command: python3 python/generateJson.py hosts
      ignore_errors: no
      register: outputJson
      tags:
        - creds

    - set_fact:
        outputRaw: "{{ outputJson.stdout | from_json }}"
      tags:
        - creds

    - set_fact:
        avi_credentials: >
                          {'api_version': "{{ aviVersion.split('-')[0] }}",
                           'controller': "{{ outputRaw | json_query('controller') }}",
                           'password': "{{ aviPassword }}",
                           'username': "{{ aviAdminUser }}"}
      tags:
        - creds

    # - name: Debug
    #   debug:
    #     msg: "{{ avi_credentials }}"
    #   tags:
    #     - creds

    - name: Update user admin password
      avi_useraccount:
        controller: "{{ avi_credentials.controller }}"
        username: "{{ avi_credentials.username }}"
        password: "{{ avi_credentials.password }}"
        old_password: 58NFaGDJm(PJH0G
        api_version: "{{ avi_credentials.api_version }}"
      ignore_errors: yes
      tags:
        - creds
        - password

    - set_fact:
        my_pass: "{{ my_pass  +  [ lookup('password', '/dev/null length=4 chars==letters') + '_' + lookup('password', '/dev/null length=4 chars==letters') | upper ] }}"
      loop: "{{ aviUser }}"
      loop_control:
        label: "Configuring {{ item.name }}"
      when: aviUser is defined
      tags:
        - creds
        - password

    # - debug:
    #     msg: "{{ item.0.name }}-{{ item.1 }}"
    #   loop: "{{ aviUser|zip(my_pass)|list }}"
    #   when: my_pass is defined

    - name: user creation
      avi_user:
        avi_credentials: "{{ avi_credentials }}"
        name: "{{ item.0.name }}"
        obj_username: "{{ item.0.name }}"
        obj_password: "{{ item.1 }}"
        access: "{{ item.0.access }}"
        user_profile_ref: "{{ item.0.user_profile_ref }}"
        is_active: "{{ item.0.is_active }}"
        is_superuser: "{{ item.0.is_superuser }}"
        default_tenant_ref: "{{ item.0.default_tenant_ref }}"
      loop: "{{ aviUser|zip(my_pass)|list }}"
      loop_control:
        label: "Configuring {{ item.0.name }}"
      when: aviUser is defined
      tags:
        - creds
        - password

    - name: Change Avi Credentials - with Ansible user
      set_fact:
        avi_credentials: >
                          {'api_version': "{{ aviVersion.split('-')[0] }}",
                          'controller': "{{ outputRaw | json_query('controller') }}",
                          'password': "{{ my_pass.0 }}",
                          'username': "{{ aviUser.0.name }}"}
      tags:
       - creds

    - name: Retrieve IP fo follower controllers - if cluster has been configured
      command: python3 python/retrieveIpFollowers.py hosts
      ignore_errors: no
      when:
        - aviCluster == 3
        - floatingIp is defined
      register: outputJson
      tags:
        - cluster

    - name: Variable change - if cluster has been configured
      set_fact:
        outputRaw: "{{ outputJson.stdout | from_json }}"
      when:
        - aviCluster == 3
        - floatingIp is defined
      tags:
        - cluster

    # - name: Debug
    #   debug:
    #     msg: "{{ outputRaw | json_query('controllerFollowerOne') }}"
    #   when:
    #     - aviCluster == 3
    #     - floatingIp is defined
    #   tags:
    #     - cluster
    #
    # - name: Debug
    #   debug:
    #     msg: "{{ outputRaw | json_query('controllerFollowerTwo') }}"
    #   when:
    #     - aviCluster == 3
    #     - floatingIp is defined
    #   tags:
    #     - cluster


    - name: Get main Cluster Information - if cluster has been configured
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        path: cluster
      register: clusterInfo
      when:
        - aviCluster == 3
        - floatingIp is defined
      tags:
        - cluster


    - name: Configure Cluster object with ClusterIP - if cluster has been configured
      avi_cluster:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        nodes:
            -
              name: "{{ avi_credentials.controller }}"
              ip:
                type: V4
                addr: "{{ avi_credentials.controller }}"
            -
              name: "{{ outputRaw | json_query('controllerFollowerOne') }}"
              ip:
                type: V4
                addr: "{{ outputRaw | json_query('controllerFollowerOne') }}"
            -
              name: "{{ outputRaw | json_query('controllerFollowerTwo') }}"
              ip:
                type: V4
                addr: "{{ outputRaw | json_query('controllerFollowerTwo') }}"
        name: aviCluster
        uuid: "{{ clusterInfo['obj'].uuid }}"
        virtual_ip:
            addr: "{{ floatingIp }}"
            type: V4
      when:
        - aviCluster == 3
        - floatingIp is defined
      tags:
        - cluster

    - name: sleep for 300 seconds and continue with play - if cluster has been configured
      wait_for: timeout=300
      when:
        - aviCluster == 3
        - floatingIp is defined
      tags:
        - cluster

    # - name: Avi credentials
    #   debug:
    #     msg: "{{ avi_credentials }}"
    #   tags:
    #     - creds

    - name: Wait for the Controller cluster to finish - if cluster has been configured
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: cluster/status
      register: statusCluster
      ignore_errors: yes
      until:
        - statusCluster.obj.cluster_state.state == "CLUSTER_UP_HA_ACTIVE"
        - statusCluster.obj.node_states.0.state == "CLUSTER_ACTIVE"
        - statusCluster.obj.node_states.1.state == "CLUSTER_ACTIVE"
        - statusCluster.obj.node_states.2.state == "CLUSTER_ACTIVE"
      retries: 120
      delay: 10
      when:
        - aviCluster == 3
        - floatingIp is defined
      tags:
        - cluster

    - name: Change Avi Credentials if cluster config has been done - with floating cluster IP - if cluster has been configured
      set_fact:
        avi_credentials: >
                          {'api_version': "{{ aviVersion.split('-')[0] }}",
                           'controller': "{{ floatingIp }}",
                           'password': "{{ my_pass.0 }}",
                           'username': "{{ aviUser.0.name }}"}
      when:
        - aviCluster == 3
        - floatingIp is defined
      tags:
        - cluster

    # - name: Updated Avi credentials
    #   debug:
    #     msg: "{{ avi_credentials }}"
    #   tags:
    #     - creds

    - name: save json creds
      copy:
        content: '{"avi_credentials": {{ avi_credentials }} }'
        dest: "vars/creds.json"
      tags:
        - creds
