---
- hosts: localhost
  gather_facts: no

  vars_files:
    - "vars/fromTerraform.yml"
    - "vars/creds.json"

  vars:
    my_pass: []

  roles:
    - role: "avinetworks.avisdk"

  tasks:


    - name: test/debug
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: cluster/status
      register: statusClusterTest
      #or status.obj.cluster_state.state == "CLUSTER_UP_NO_HA"
      retries: 120
      delay: 10
      when:
        - aviCluster == 3
        - floatingIp is defined
      tags:
        - cluster
        - debug

    - name: DebugOne
      debug:
        msg: "{{ statusClusterTest.obj }}"
      tags:
        - debug


    - name: DebugTwo
      debug:
        msg: "{{ statusClusterTest.obj.cluster_state.state }}"
      tags:
        - debug

    - name: Wait for the Controller cluster to finish
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: cluster/status
      register: statusCluster
      until:
        - statusCluster.obj.cluster_state.state == "CLUSTER_UP_HA_ACTIVE"
        - statusCluster.obj.node_states.0.state == "CLUSTER_ACTIVE"
        - statusCluster.obj.node_states.1.state == "CLUSTER_ACTIVE"
        - statusCluster.obj.node_states.2.state == "CLUSTER_ACTIVE"
      #or status.obj.cluster_state.state == "CLUSTER_UP_NO_HA"
      retries: 120
      delay: 10
      when:
        - aviCluster == 3
        - floatingIp is defined
      tags:
        - cluster
        - debug

    - name: Debug
      debug:
        msg: "{{ statusCluster.obj.cluster_state.state }}"
      tags:
        - debug

    - name: Debug
      debug:
        msg: "{{ statusCluster.obj.node_states.0.state }}"
      tags:
        - debug

    - name: Debug
      debug:
        msg: "{{ statusCluster.obj.node_states.1.state }}"
      tags:
        - debug

    - name: Debug
      debug:
        msg: "{{ statusCluster.obj.node_states.2.state }}"
      tags:
        - debug
